.PHONY: run build test tidy docker-up migrate-up migrate-down migrate-status migrate-create

run:
	go run ./cmd/api

build:
	go build -o bin/api ./cmd/api

test:
	go test ./...

tidy:
	go mod tidy

docker-up:
	docker compose up --build

migrate-up:
	go run ./cmd/api migrate up

migrate-down:
	go run ./cmd/api migrate down

migrate-status:
	go run ./cmd/api migrate status

# Usage: make migrate-create name=add_payments
migrate-create:
	go run ./cmd/api migrate create $(name)
